name: GitHub Self-Updating Repository

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v4
        with:
          ref: ics
      - name: Create GenG.ics
        run: |
          npm install
          npm start
      - name: Push to repository
        run: |
          git config --global user.name "GenG Calendar"
          git config --global user.email "vitalitycal25@gmail.com"
          git add GenG.ics
          git commit -m "Update GenG.ics"
          git push -u origin ics
